dc_linux() {
cat > $root/etc/os-release <<-EOT
NAME="Dreamcast Linux"
PRETTY_NAME="Dreamcast Linux (`date +%Y-%m-%d`)"
ID=dclinux
ID_LIKE=t2sde
VERSION="`date +%Y-%m-%d`"
VERSION_ID=`date +%Y-%m-%d`
HOME_URL="https://github.com/foxdrodd/dreamcast-linux"
BUG_REPORT_URL="https://github.com/foxdrodd/dreamcast-linux/issues"
EOT
}

hook_add postinstall 5 dc_linux
