add_telnetd_conf() {
        cat > $root/etc/xinetd.d/telnetd <<-EOF
service telnet
{
    disable         = no
    socket_type     = stream
    protocol        = tcp
    wait            = no
    user            = root
    server          = /usr/libexec/telnetd
    server_args     = -E /usr/bin/rootlogin
    flags           = REUSE
    log_on_failure  += USERID
}
EOF

        cat > $root/usr/bin/rootlogin <<-EOF
#!/bin/sh
exec /bin/sh
EOF

chmod a+x $root/usr/bin/rootlogin
}

hook_add postmake 5 add_telnetd_conf
